// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt6pIz3PcswyKsnzGFdcv4_kRJ93n5CUQ',
    appId: '1:581291310412:web:60a61e86c76256ab1023e9',
    messagingSenderId: '581291310412',
    projectId: 'riogas-pedidos',
    authDomain: 'riogas-pedidos.firebaseapp.com',
    databaseURL: 'https://riogas-pedidos-default-rtdb.firebaseio.com',
    storageBucket: 'riogas-pedidos.firebasestorage.app',
    measurementId: 'G-0WT2RJ8Y0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM0Hn6fXIrD2r42q0avKD2gZ5kzqaxaUM',
    appId: '1:581291310412:android:9ab960ac4b55a1f71023e9',
    messagingSenderId: '581291310412',
    projectId: 'riogas-pedidos',
    databaseURL: 'https://riogas-pedidos-default-rtdb.firebaseio.com',
    storageBucket: 'riogas-pedidos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFoOlmGS5y11Om1c18blPsRKgbB1ps-6k',
    appId: '1:581291310412:ios:249f949e4077fee61023e9',
    messagingSenderId: '581291310412',
    projectId: 'riogas-pedidos',
    databaseURL: 'https://riogas-pedidos-default-rtdb.firebaseio.com',
    storageBucket: 'riogas-pedidos.firebasestorage.app',
    iosBundleId: 'com.example.appmovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFoOlmGS5y11Om1c18blPsRKgbB1ps-6k',
    appId: '1:581291310412:ios:249f949e4077fee61023e9',
    messagingSenderId: '581291310412',
    projectId: 'riogas-pedidos',
    databaseURL: 'https://riogas-pedidos-default-rtdb.firebaseio.com',
    storageBucket: 'riogas-pedidos.firebasestorage.app',
    iosBundleId: 'com.example.appmovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt6pIz3PcswyKsnzGFdcv4_kRJ93n5CUQ',
    appId: '1:581291310412:web:dfc59101f189d4cd1023e9',
    messagingSenderId: '581291310412',
    projectId: 'riogas-pedidos',
    authDomain: 'riogas-pedidos.firebaseapp.com',
    databaseURL: 'https://riogas-pedidos-default-rtdb.firebaseio.com',
    storageBucket: 'riogas-pedidos.firebasestorage.app',
    measurementId: 'G-0Y5WCTYT14',
  );
}
